services:
  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    networks:
      - net_gochat
    healthcheck:
      test: ["CMD", "mongo", "--eval", "printjson(db.adminCommand('ping'))"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
 
  nats:
      image: nats:latest
      container_name: natsgo
      ports:
        - "4222:4222"        
        - "6222:6222"       
        - "8222:8222"      
        - "8080:8080"   
      volumes:
        - ./nats-server.conf:/etc/nats/nats-server.conf  # Asegúrate de que el archivo esté en el directorio correcto
        - nats_data:/data
      entrypoint: ["/nats-server", "-c", "/etc/nats/nats-server.conf"]  # Aquí usamos el formato correcto para Docker
      restart: always
      environment:
        - JS_ENABLE=true         
      networks:
        - net_gochat

volumes:
  mongodb_data:
  nats_data: 

networks:
  net_gochat:
    driver: bridge