services:
  nats:
    image: nats:latest
    container_name: natsgo
    ports:
      - "4222:4222"        
      - "6222:6222"       
      - "8222:8222"        
    volumes:
      - nats_data:/data   
    command:
      - "-js"
      - "--store_dir"
      - "/data"
      - "--http_port"
      - "8222"
    restart: always
    environment:
      - JS_ENABLE=true         
    networks:
      - net_gochat

volumes:
  mongodb_data:
  nats_data: 

networks:
  net_gochat:
    driver: bridge